# Fluent Bit ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Log_Level warn
    [INPUT]
        Name tail
        Path /tmp/ray/session_*/logs/*
        Tag *
        Refresh_Interval 2
    [FILTER]
        Name record_modifier
        Match *
        Record hostname ${HOSTNAME}
    [FILTER]
        Name rewrite_tag
        Match_Regex ^tmp.ray.session_([^.]*).logs.job-driver-(.*)$
        Rule $log ^(.*)$ $TAG[2]/$TAG[4].$TAG[5] true
    [FILTER]
        Name rewrite_tag
        Match_Regex ^tmp.ray.session_([^.]*).logs.job-driver-(.*)$
        Rule $log ^(.*)$ $TAG[4] false
    [FILTER]
        Name stdout
        Match job-driver-*
    [FILTER]
        Name rewrite_tag
        Match tmp.ray.session_*
        Rule $log ^(.*)$ $TAG[2]/etc/$TAG[4].$TAG[5] false
    [OUTPUT]
        Name azure_blob
        Match session_*
        account_name "AZURE_ACCOUNT_NAME"
        shared_key "SHARED_KEY"
        container_name ray-logs
        blob_type appendblob
        auto_create_container on
        tls on
---
# This config demonstrates KubeRay's Ray autoscaler integration.
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: raycluster-autoscaler
  # annotations:
    # ray.io/ft-enabled: "true" # <- add this annotation enable GCS FT
    # ray.io/external-storage-namespace: "external-storage-namespace-name"
spec:
  rayVersion: '2.3.0'
  enableInTreeAutoscaling: true
  headGroupSpec:
    replicas: 0
    # Kubernetes Service Type, valid values are 'ClusterIP', 'NodePort' and 'LoadBalancer'
    serviceType: 'LoadBalancer'
    enableIngress: true
    # the following params are used to complete the ray start: ray start --head --block ...
    rayStartParams:
      dashboard-host: '0.0.0.0'
      block: "true"
      metrics-export-port: "9001"
    template:
      metadata:
        labels:
          rayCluster: raycluster-autoscaler # will be injected if missing
          rayNodeType: head # will be injected if missing, must be head or worker
          groupName: headgroup # will be injected if missing
      spec:
        containers:
        # The Ray head container
        - name: ray-head
          image: "RAY_IMAGE"
          imagePullPolicy: Always
          ports:
          - containerPort: 10001
            name: client
            protocol: TCP
          - containerPort: 8265
            name: dashboard
            protocol: TCP
          - containerPort: 8000
            name: serve
            protocol: TCP
          - containerPort: 6379
            name: gcs
            protocol: TCP
          - containerPort: 9001
            name: metrics
            protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c", "-l","ray stop"]
          resources:
            limits:
              cpu: 4
              memory: 6Gi
            requests:
              cpu: 4
              memory: 6Gi
          volumeMounts:
            - mountPath: /tmp/ray
              name: ray-logs
        # Fluent Bit sidecar
        - name: fluentbit
          image: fluent/fluent-bit:1.9.6
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
          - mountPath: /tmp/ray
            name: ray-logs
          - mountPath: /fluent-bit/etc/fluent-bit.conf
            subPath: fluent-bit.conf
            name: fluentbit-config
        # Log and config volumes
        volumes:
        - name: ray-logs
          emptyDir: {}
        - name: fluentbit-config
          configMap:
            name: fluentbit-config
  workerGroupSpecs:
  # the pod replicas in this group typed worker
  - replicas: 1
    minReplicas: 1
    maxReplicas: 5
    # logical group name, for this called small-group, also can be functional
    groupName: worker-group
    # the following params are used to complete the ray start: ray start --block ...
    rayStartParams:
      metrics-export-port: "9001"
      block: "true"
    # pod template
    template:
      spec:
        initContainers:
        # the env var $RAY_IP is set by the operator if missing, with the value of the head service name
        - name: init
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for K8s Service $RAY_IP; sleep 2; done"]
        containers:
        - name: ray-worker
          image: "RAY_IMAGE"
          env:
          - name: TYPE
            value: "worker"
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","-l","ray stop"]
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
          volumeMounts:
          - mountPath: /tmp/ray
            name: ray-logs
        # Fluent Bit sidecar
        - name: fluentbit
          image: fluent/fluent-bit:1.9.6
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
          - mountPath: /tmp/ray
            name: ray-logs
          - mountPath: /fluent-bit/etc/fluent-bit.conf
            subPath: fluent-bit.conf
            name: fluentbit-config
        # Log and config volumes
        volumes:
        - name: ray-logs
          emptyDir: {}
        - name: fluentbit-config
          configMap:
            name: fluentbit-config
