apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ray_cluster-azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 200Gi